name: Trigger Twitter Quote Bot

on:
  schedule:
    # Runs at 8:00 AM, 2:00 PM, and 8:00 PM UTC every day
    - cron: '0 8 * * *'  # 8 AM UTC
    - cron: '0 14 * * *' # 2 PM UTC
    - cron: '0 20 * * *' # 8 PM UTC
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  trigger-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request to Render
        run: |
          curl -X GET "https://your-service-name.onrender.com/run" \
          -H "Accept: application/json"
        env:
          RENDER_WEBHOOK_URL: ${{ secrets.RENDER_WEBHOOK_URL }} # Optional: if you need authentication

      - name: Check Response
        run: |
          echo "Triggered Twitter Quote Bot successfully!"